name: Test Python code

on:
  pull_request:
    paths:
      - '.github/workflows/test-python.yml'
      - 'compilesketches/**'

  push:
    paths:
      - '.github/workflows/test-python.yml'
      - 'compilesketches/**'

  # The actions/setup-python action will periodically break the workflow by dropping the Python version we have pinned
  # Better to catch that before it causes confusion for a contributor
  schedule:
    # run every Tuesday at 3 AM UTC
    - cron: "0 3 * * 2"

  # workflow_dispatch event allows the workflow to be triggered manually
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

  # repository_dispatch event allows the workflow to be triggered via the GitHub API
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHON_PROJECT_PATH: ${GITHUB_WORKSPACE}/compilesketches
      PYTHON_PROJECT_TESTS_PATH: ${GITHUB_WORKSPACE}/compilesketches/tests

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement "${{ env.PYTHON_PROJECT_TESTS_PATH }}/requirements.txt"

      - name: Run Python unit tests and report code coverage
        run: |
          export PYTHONPATH="${{ env.PYTHON_PROJECT_PATH }}"
          coverage run --source="${{ env.PYTHON_PROJECT_PATH }}" --module pytest "${{ env.PYTHON_PROJECT_TESTS_PATH }}"
          # Display code coverage report in workflow run log
          coverage report

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
